// 120-Day Practical SEO + AI Search + Local SEO + GEO/AEO Course
// Transcribed from Outreach_Recruitment_120_Day_SEO_AI_Local_GEO_Course.pdf
window.COURSE = {
  title: "120-Day Practical SEO + AI Search + Local SEO + GEO/AEO Course",
  objective:
    "Build a repeatable SEO system that grows qualified organic visibility, job applications and employer enquiries while moving priority Malta recruitment keywords toward the Top 10.",
  principle: "Learn → Practice → Measure → Review → Improve",
  weights: { qcm: 20, practical: 35, tracking: 20, monthly: 15, final: 10 },
  passMark: 70,
  dailyRhythm: [
    "Learn the concept + record baseline data",
    "Audit Outreach Recruitment using the concept",
    "Implement the first practical change",
    "Continue implementation + internal QA",
    "Measure early signals + document work",
    "Complete practice exercise + QCM",
    "Weekly report, résumé and next-week priority",
  ],
  months: [
    { n: 1, weeks: [1, 2, 3, 4], goal: "Reliable analytics baseline, keyword map, on-page improvements and technical priority list." },
    { n: 2, weeks: [5, 6, 7, 8], goal: "Sector/topic authority system, employer content and an evidence-based content refresh process." },
    { n: 3, weeks: [9, 10, 11, 12], goal: "Local visibility plan, legitimate citation/backlink pipeline and a digital PR asset concept." },
    { n: 4, weeks: [13, 14, 15, 16], goal: "AEO/GEO improvements, AI visibility benchmark, final KPI comparison and next 90-day strategy." },
  ],
  worksheet: [
    "What did I change on the website?",
    "What data did I record before the change?",
    "What result do I expect?",
    "When will I review it? (7d / 30d / 60d / 90d)",
    "What did I learn?",
  ],
  weeks: [
    {
      n: 1, track: "SEO", title: "SEO Foundations, Search Console & GA4",
      objective: "Understand how crawling, indexing, ranking and measurement connect. Establish a reliable baseline before changing the site.",
      understand: "SEO performance is a chain. Google must discover and index a page; the page must match a query; the search result must earn the click; the landing page must satisfy the visitor; and the visitor should complete a useful action. Search Console explains search visibility, while GA4 explains what happens after the visit.",
      tasks: [
        "Map the candidate journey: Google search → landing page → job → application.",
        "Map the employer journey: Google search → employer/service page → enquiry.",
        "Record 28-day and 3-month Search Console baselines.",
        "Record GA4 organic acquisition and top landing pages.",
        "Define application and employer-lead conversions.",
      ],
      qcm: [
        "What is the difference between crawling and indexing?",
        "Which Search Console metric tells you how often a result was shown?",
        "Why is average position not enough by itself?",
        "What is the difference between a user, session and conversion?",
        "Why should SEO track applications instead of only traffic?",
      ],
      answers: "Crawling discovers; indexing stores/understands eligible pages. Impressions = appearances. Position alone needs clicks/CTR/conversions. Users are people, sessions are visits, conversions are desired actions. SEO should connect to business outcomes.",
      deliverable: "Baseline SEO & Analytics Report",
      tracker: "kpi_daily",
    },
    {
      n: 2, track: "SEO", title: "Keyword Research & Search Intent",
      objective: "Build a keyword universe around candidates, sectors, employers and Malta recruitment intent.",
      understand: "Keyword research is demand research. For Outreach Recruitment, one keyword database must cover both sides of the marketplace: candidates looking for jobs and employers looking for recruitment support. Search intent determines the correct page type.",
      tasks: [
        "Export real Search Console queries and label them by intent.",
        "Research general terms: jobs in Malta, recruitment agency Malta, job vacancies Malta.",
        "Build sector groups: hospitality, engineering, finance, logistics, manufacturing, construction, IT, sales, customer care, marine.",
        "Build employer groups: hire staff Malta, recruitment services Malta, find employees Malta.",
        "Assign one primary target page to each important keyword.",
      ],
      qcm: [
        "What is search intent?",
        "When should two similar keywords share one page?",
        "What is a long-tail keyword?",
        "Why can a low-volume employer keyword be valuable?",
        "What is keyword cannibalization?",
      ],
      answers: "Intent = what the searcher wants. Similar queries can share a page when intent is the same. Long-tail queries are more specific. Low-volume employer terms can have high commercial value. Cannibalization occurs when multiple pages compete for the same intent.",
      deliverable: "Keyword Master Sheet",
      tracker: "keywords",
    },
    {
      n: 3, track: "SEO", title: "On-Page SEO & Internal Linking",
      objective: "Turn keyword research into clear, useful pages that match intent and guide users toward applications or employer enquiries.",
      understand: "On-page SEO communicates page purpose. Titles, headings, copy, internal links and CTAs should all support the same intent. Optimization should make a page clearer, not simply repeat a keyword.",
      tasks: [
        "Audit homepage title, H1 and primary intent.",
        "Audit /jobs/ and /employers/.",
        "Create title/meta/H1 recommendations for five priority pages.",
        "Build internal links from blogs to sectors, sectors to jobs and jobs back to sector hubs.",
        "Check image alt text and CTA clarity.",
      ],
      qcm: [
        "What is the role of an H1?",
        "Does a meta description directly guarantee rankings?",
        "Why are internal links useful?",
        "What is anchor text?",
        "What is the danger of keyword stuffing?",
      ],
      answers: "H1 communicates the main page topic. Meta descriptions can influence clicks but are not a ranking guarantee. Internal links aid discovery, context and navigation. Anchor text describes the destination. Keyword stuffing harms readability and quality.",
      deliverable: "On-Page Optimization Sheet",
      tracker: "pages",
    },
    {
      n: 4, track: "SEO", title: "Technical SEO for a Recruitment Website",
      objective: "Make important pages crawlable, indexable, fast and technically understandable, with special attention to job listings.",
      understand: "Recruitment sites change quickly because jobs appear and expire. Technical SEO must prevent stale listings, duplicate URLs and poor indexing from wasting crawl attention or disappointing users.",
      tasks: [
        "Audit sitemap and robots directives.",
        "Check canonical URLs and duplicate/filter URLs.",
        "Review expired-job handling.",
        "Validate representative JobPosting structured data.",
        "Check mobile performance and Core Web Vitals.",
        "Create severity levels: Critical / High / Medium / Low.",
      ],
      qcm: [
        "What does a canonical URL communicate?",
        "What should happen when a job expires?",
        "What is structured data?",
        "Why can filter URLs create SEO problems?",
        "Name the three Core Web Vitals.",
      ],
      answers: "Canonicals indicate the preferred URL. Expired jobs need an accurate removal/update strategy. Structured data provides machine-readable page information. Filter URLs can multiply duplicates. Core Web Vitals: LCP, INP, CLS.",
      deliverable: "Technical SEO Audit",
      tracker: "technical_issues",
    },
    {
      n: 5, track: "SEO", title: "Sector Landing Pages",
      objective: "Create permanent sector resources that can rank even when individual job listings change.",
      understand: "Individual vacancies are temporary. Permanent sector landing pages provide stable URLs around important themes such as hospitality, engineering and finance while continually linking users to current jobs.",
      tasks: [
        "Build or improve Hospitality Jobs Malta.",
        "Choose a second sector from Search Console opportunity data.",
        "Add current vacancies dynamically or manually where appropriate.",
        "Add sector-specific FAQs and useful candidate guidance.",
        "Link to relevant individual jobs and supporting guides.",
      ],
      qcm: [
        "Why should a sector page be permanent?",
        "What is the difference between a sector page and a job detail page?",
        "What makes a sector page useful beyond a job list?",
        "How should expired jobs affect the sector page?",
        "Which KPI would you watch first after publishing?",
      ],
      answers: "Permanent sector pages provide stable thematic targets. Job pages represent individual vacancies. Strong sector pages add useful sector guidance, current roles and FAQs. Expired jobs should not make the sector hub disappear. Watch indexing/impressions first, then clicks/conversions.",
      deliverable: "2 Optimized Sector Pages",
      tracker: "pages",
    },
    {
      n: 6, track: "SEO", title: "Topic Clusters & Topical Authority",
      objective: "Connect related resources so search engines and users can understand the depth of Outreach Recruitment's Malta jobs expertise.",
      understand: "A topic cluster creates relationships between a broad pillar topic and supporting resources. This improves navigation and makes it easier to demonstrate comprehensive coverage of Malta recruitment topics.",
      tasks: [
        "Create a Jobs in Malta pillar-page plan.",
        "Map supporting sector pages.",
        "Map CV, interview and job-search guides.",
        "Add contextual internal links.",
        "Identify orphan pages and connect them.",
      ],
      qcm: [
        "What is a pillar page?",
        "What is a topic cluster?",
        "Why are orphan pages a problem?",
        "What makes an internal link contextual?",
        "How can clusters help users as well as SEO?",
      ],
      answers: "Pillar = broad central resource. Cluster = related supporting content. Orphans lack internal links. Contextual links appear naturally within relevant content. Clusters improve discovery and user journeys.",
      deliverable: "Malta Jobs Topic Cluster Map",
      tracker: "content_items",
    },
    {
      n: 7, track: "SEO", title: "Employer SEO & Commercial Content",
      objective: "Generate employer-side organic leads, not only candidate traffic.",
      understand: "Candidate traffic is only one business outcome. Employer SEO targets companies that need hiring support, so conversion tracking and commercial content are essential.",
      tasks: [
        "Optimize /employers/ around genuine employer intent.",
        "Plan 'How to Hire Employees in Malta'.",
        "Plan 'Recruitment Process in Malta'.",
        "Add proof, process, sectors served and clear enquiry CTA.",
        "Track employer form submissions as a conversion.",
      ],
      qcm: [
        "What is commercial search intent?",
        "Why can employer traffic be more valuable than high-volume candidate traffic?",
        "What should an employer landing page prove?",
        "What is a conversion CTA?",
        "Which analytics event should be tracked?",
      ],
      answers: "Commercial intent indicates a user may buy/use a service. Employer queries can create high-value leads. Employer pages should prove service, expertise/process and relevance. CTA = desired action. Track employer enquiry submission.",
      deliverable: "Employer SEO Funnel",
      tracker: "content_items",
    },
    {
      n: 8, track: "SEO", title: "Content Quality, Refreshing & SEO Decisions",
      objective: "Learn to decide whether to improve, consolidate, keep or remove content using performance data.",
      understand: "Publishing is not the finish line. Search Console and GA4 tell you which pages deserve more support, which titles need better CTR, which pages need updating and which content does not create business value.",
      tasks: [
        "Compare pages by impressions, clicks, CTR and conversions.",
        "Find pages ranking 4-20.",
        "Find high-impression/low-CTR pages.",
        "Find weak or outdated content.",
        "Create a 30-day refresh queue.",
      ],
      qcm: [
        "What is a high-impression/low-CTR opportunity?",
        "Why are positions 4-20 important?",
        "When might two articles be consolidated?",
        "What does content freshness mean?",
        "Why should conversions influence content decisions?",
      ],
      answers: "High impressions/low CTR can indicate snippet or intent opportunity. Positions 4-20 are close enough to prioritize. Consolidate overlapping content when one stronger page can satisfy the same intent. Freshness means keeping changing information accurate. Conversions show business value.",
      deliverable: "Content Optimization Queue",
      tracker: "live",
    },
    {
      n: 9, track: "Local SEO", title: "Local SEO for Malta",
      objective: "Strengthen accurate local relevance without creating misleading location signals.",
      understand: "Local SEO is based on accurate real-world business information and genuine local relevance. Avoid creating signals that do not reflect the business's actual operations.",
      tasks: [
        "Audit business information consistency.",
        "Review Google Business Profile eligibility and completeness where applicable.",
        "Review service/market descriptions.",
        "Build a review acquisition process that follows platform rules.",
        "Track branded/local queries.",
      ],
      qcm: [
        "What are relevance, distance and prominence?",
        "Why must business information be accurate?",
        "Can distance simply be optimized away?",
        "Why do reviews matter to users?",
        "What makes a local page genuinely useful?",
      ],
      answers: "Local ranking concepts include relevance, distance and prominence. Business information must reflect reality. Distance is based on searcher/business context, not a trick. Reviews help trust and prominence. Local pages need genuine local usefulness.",
      deliverable: "Local SEO Audit",
      tracker: "local_actions",
    },
    {
      n: 10, track: "Local SEO", title: "Location Content & Citations",
      objective: "Build location relevance only where Outreach genuinely serves users and has unique information to provide.",
      understand: "Location pages should exist because they help users, not because a city name can be inserted into a template. Citations should be legitimate references to the real business.",
      tasks: [
        "Evaluate Valletta, Sliema, St Julian's, Msida, Gozo and other Malta locations from demand/data.",
        "Avoid near-duplicate city pages.",
        "Find relevant Malta business/recruitment citations.",
        "Check consistent company information.",
        "Create one location-page brief.",
      ],
      qcm: [
        "What is a doorway page risk?",
        "Why should location pages contain unique value?",
        "What is a citation?",
        "Why does NAP/business consistency matter?",
        "How do you prioritize locations?",
      ],
      answers: "Doorway-like pages are thin near-duplicates created mainly to capture locations. Unique local value prevents this pattern. Citations are legitimate business references/listings. Consistency reduces ambiguity. Prioritize locations using real service relevance and demand.",
      deliverable: "Location & Citation Plan",
      tracker: "local_actions",
    },
    {
      n: 11, track: "Authority", title: "Backlinks & Outreach",
      objective: "Earn relevant authority through partners, resources and useful contributions rather than bulk low-quality links.",
      understand: "Backlinks are recommendations between webpages, but relevance and legitimacy matter. A smaller number of strong industry/partner links can be more useful than bulk directory spam.",
      tasks: [
        "Find 20 relevant prospects.",
        "Score each for relevance and legitimacy.",
        "Identify partner-link opportunities.",
        "Create an outreach message.",
        "Track replies and acquired links.",
      ],
      qcm: [
        "What makes a backlink relevant?",
        "Is a large number of links always better?",
        "What is anchor text?",
        "What is a referring domain?",
        "Why are paid/spam link schemes risky?",
      ],
      answers: "Relevant links come from contextually appropriate legitimate sites. Quantity alone is not quality. Anchor text is linked text. A referring domain is a unique website linking to you. Spam/paid schemes can violate search-engine guidelines.",
      deliverable: "Backlink Prospect Tracker",
      tracker: "backlinks",
    },
    {
      n: 12, track: "Authority", title: "Digital PR & Linkable Assets",
      objective: "Create something other websites have a genuine reason to cite.",
      understand: "Digital PR earns attention by creating useful information. Recruitment data, hiring trends and sector insights can become assets that partners, media or employers may choose to reference.",
      tasks: [
        "Design a Malta Recruitment & Jobs Report concept.",
        "List first-party data Outreach can responsibly aggregate.",
        "Add trustworthy external sources where needed.",
        "Create a statistics/resource page outline.",
        "Build a distribution list of relevant publications/partners.",
      ],
      qcm: [
        "What is a linkable asset?",
        "Why is original data valuable?",
        "Why must statistics have sources and dates?",
        "What is digital PR?",
        "How can a resource earn links naturally?",
      ],
      answers: "Linkable assets give others a reason to cite you. Original data can be distinctive. Statistics need provenance and dates. Digital PR earns coverage through newsworthy/useful material. Useful resources attract voluntary references.",
      deliverable: "Digital PR Resource Brief",
      tracker: "backlinks",
    },
    {
      n: 13, track: "AI Search / AEO / GEO", title: "AEO – Answer Engine Optimization",
      objective: "Answer real candidate and employer questions clearly and efficiently while keeping pages useful for deeper reading.",
      understand: "AEO focuses on answering questions. The best pattern is often a short, direct answer first, then supporting detail, examples and links for users who need more depth.",
      tasks: [
        "Collect 50 questions from Search Console, SERPs and customer/candidate experience.",
        "Group by candidate, employer, sector and location.",
        "Write concise direct answers followed by detail.",
        "Add FAQs only when they genuinely help the page.",
        "Link answers to deeper resources.",
      ],
      qcm: [
        "What is AEO?",
        "Why should the direct answer appear early?",
        "Should every page have dozens of FAQs?",
        "How do question headings help users?",
        "Why must answers remain accurate and updated?",
      ],
      answers: "AEO = optimizing useful answers to questions. Direct answers reduce effort. FAQs should exist only when useful. Question headings mirror user needs. Answers must stay accurate.",
      deliverable: "50-Question AEO Map",
      tracker: "content_items",
    },
    {
      n: 14, track: "AI Search / AEO / GEO", title: "GEO – Generative Engine Optimization",
      objective: "Improve clarity, evidence and entity relationships so content is easier for AI-powered search systems to interpret and reference.",
      understand: "GEO is not a replacement for SEO. It emphasizes clear entities, evidence, source quality, factual precision and content structures that are easy to retrieve and summarize.",
      tasks: [
        "Clarify Outreach Recruitment's entity information.",
        "Add dates, authorship/context and sources where useful.",
        "Replace vague claims with verifiable evidence.",
        "Use structured headings, tables and concise definitions.",
        "Upgrade one major guide into a citation-worthy resource.",
      ],
      qcm: [
        "What does GEO try to improve?",
        "Why are verifiable sources important?",
        "What is entity clarity?",
        "Why are unsupported claims weak?",
        "How does GEO complement rather than replace SEO?",
      ],
      answers: "GEO improves retrievability/citability for generative systems through clarity and evidence. Sources support trust. Entity clarity makes people/organizations/topics unambiguous. Unsupported claims are hard to verify. GEO complements technical/on-page SEO.",
      deliverable: "GEO-Optimized Resource",
      tracker: "content_items",
    },
    {
      n: 15, track: "AI Search / AEO / GEO", title: "AI Search Visibility Tracking",
      objective: "Create a repeatable benchmark instead of relying on anecdotes about whether AI systems mention the brand.",
      understand: "AI visibility is still evolving, so measure carefully. Use a fixed question set and dated observations, and prioritize measurable referral traffic when available.",
      tasks: [
        "Choose 20 stable questions.",
        "Record date, query, system/search experience and result.",
        "Record whether Outreach is surfaced, cited or receives measurable referral traffic.",
        "Compare answers to competitors without manipulating tests.",
        "Repeat on a consistent schedule.",
      ],
      qcm: [
        "Why must AI visibility tests use consistent questions?",
        "Why should results be dated?",
        "What is referral traffic?",
        "Why is one AI answer not enough to prove a trend?",
        "How can better source content help?",
      ],
      answers: "Consistent questions improve comparability. Dates matter because systems change. Referral traffic is traffic arriving from another source. One answer is anecdotal, not a trend. Strong source content gives systems better material to retrieve.",
      deliverable: "AI Visibility Benchmark",
      tracker: "ai_visibility",
    },
    {
      n: 16, track: "Analytics", title: "Final Analysis & 90-Day Growth Plan",
      objective: "Turn 120 days of work into decisions and a repeatable operating system.",
      understand: "The final skill is decision-making. A good SEO practitioner can explain what changed, why it may have changed, what evidence supports the conclusion and what action should happen next.",
      tasks: [
        "Compare Day 1 vs Day 120.",
        "Identify winning pages and near-Top-10 opportunities.",
        "Identify pages with traffic but poor conversion.",
        "Identify technical work still open.",
        "Create the next 90-day priorities based on impact and effort.",
      ],
      qcm: [
        "Which metrics prove visibility growth?",
        "Which metrics prove business impact?",
        "How do you identify a near-Top-10 opportunity?",
        "Why compare equivalent date ranges?",
        "What should determine the next 90-day priorities?",
      ],
      answers: "Visibility: impressions/rankings/clicks. Business impact: conversions/leads/applications. Near-Top-10 often means positions 11-20. Equivalent ranges reduce seasonality/date bias. Priorities should be based on evidence, impact, effort and business goals.",
      deliverable: "120-Day SEO Case Study",
      tracker: "final",
    },
  ],
  decisionFramework: [
    { t: "High impressions + low CTR", d: "Investigate whether the title/snippet matches intent, whether the page is ranking for the right queries, and whether competing results provide a clearer proposition. Do not change titles every day; test changes over meaningful periods." },
    { t: "Position 4-10", d: "Protect and strengthen the page. Improve completeness, internal links, freshness, conversion path and relevant authority. These keywords are already on page one and can be high-value opportunities." },
    { t: "Position 11-20", d: "Treat these as strong growth candidates. Compare search intent, missing subtopics, page quality, internal links and external authority." },
    { t: "Traffic growing but applications flat", d: "SEO may be attracting the wrong audience or the conversion path may be weak. Review job relevance, page clarity, CTA placement, form friction and traffic geography." },
    { t: "Applications growing but traffic flat", d: "Conversion quality may have improved. Identify which pages or changes increased conversion rate and replicate the learning." },
    { t: "Indexed pages rising but traffic does not", d: "More indexed pages are not automatically better. Check whether new pages target real demand, avoid duplication and provide unique value." },
  ],
  sectors: [
    ["Hospitality", "hospitality jobs Malta", "hotel, restaurant, chef, F&B, housekeeping, front office"],
    ["Engineering", "engineering jobs Malta", "mechanical, electrical, maintenance, technical roles"],
    ["Finance", "finance jobs Malta", "accounting, audit, finance operations"],
    ["Logistics", "logistics jobs Malta", "warehouse, storekeeper, forklift, driver"],
    ["Manufacturing", "manufacturing jobs Malta", "production, factory, industrial, operators"],
    ["Construction", "construction jobs Malta", "carpentry, gypsum, installation, trades"],
    ["IT", "IT jobs Malta", "software, support, systems, technology"],
    ["Customer Care", "customer service jobs Malta", "contact centre, support, team leader"],
    ["Marine", "marine jobs Malta", "shipping, shipyard, maritime, marine engineering"],
  ],
  competencies: [
    "I can audit a website without relying on a checklist alone.",
    "I can map keywords to the correct page type.",
    "I can use Search Console and GA4 to make decisions.",
    "I can optimize recruitment/job pages without keyword stuffing.",
    "I can identify technical indexing and structured-data issues.",
    "I can build topic clusters and internal links.",
    "I can plan legitimate local SEO and link-building work.",
    "I can create AEO/GEO-friendly, evidence-based resources.",
    "I can connect SEO traffic to applications and employer leads.",
    "I can produce a monthly SEO report and next-action plan.",
  ],
};
