/* Week-specific measurement plans. These turn KPI movement into a focused course action. */
window.COURSE_METRICS = {
  1: { question: "Is measurement complete and are organic visits producing real candidate or employer actions?", kpis: ["organic_users", "applications", "employer_leads"], source: "GA4 Acquisition + Realtime, Search Console Performance", action: "Fix missing tracking first; do not optimise pages until the baseline and conversion events are reliable." },
  2: { question: "Are the right Malta queries gaining visibility and sending qualified visits?", kpis: ["impressions", "clicks", "avg_position"], source: "Search Console Queries + Keywords tracker", action: "Prioritise one high-impression query with position 4–20, confirm its intent, and assign one best target page." },
  3: { question: "Did clearer titles, page copy and internal links improve discovery and clicks?", kpis: ["ctr", "clicks", "avg_position"], source: "Search Console Pages/Queries + Experiments tracker", action: "If impressions are stable but CTR falls, improve the title/description; if position falls, review intent, content and internal links." },
  4: { question: "Are technical fixes making important job pages eligible and visible?", kpis: ["impressions", "clicks", "avg_position"], source: "Search Console Pages/Indexing + Technical tracker", action: "Resolve the highest-severity crawl, canonical or JobPosting issue, validate it, and annotate the fix date before judging KPI impact." },
  5: { question: "Are permanent sector pages building visibility and sending candidates to relevant jobs?", kpis: ["impressions", "clicks", "applications"], source: "Search Console page filter + GA4 landing pages + Sector opportunities", action: "Improve the sector page with the strongest combination of search demand and live jobs; review impressions first, then applications after 30 days." },
  6: { question: "Are topic clusters helping users and Google discover the priority pages?", kpis: ["impressions", "clicks", "organic_users"], source: "Search Console Pages/Links + GA4 landing pages + Technical orphan audit", action: "Add contextual links to one under-supported pillar or sector page, then check discovery and landing-page traffic after 30 days." },
  7: { question: "Is employer-focused organic traffic generating qualified hiring enquiries?", kpis: ["organic_users", "employer_leads", "ctr"], source: "GA4 organic landing pages/events + Search Console employer queries", action: "If employer traffic rises without leads, improve proof and the enquiry CTA; if visibility is weak, strengthen employer-intent content first." },
  8: { question: "Which existing pages have the clearest measurable refresh opportunity?", kpis: ["impressions", "ctr", "avg_position"], source: "Search Console Pages + Pages and Experiments trackers", action: "Select one page at position 4–20 or with high impressions and low CTR; make one focused change and set a 30-day review." },
  9: { question: "Is local visibility contributing to branded discovery and useful website visits?", kpis: ["clicks", "organic_users", "employer_leads"], source: "Search Console branded queries + GA4 organic/local landing pages + Local tracker", action: "Correct the most important NAP/profile inconsistency, record evidence, and compare branded clicks and leads monthly." },
  10: { question: "Do location pages have enough real demand and job supply to justify them?", kpis: ["impressions", "clicks", "applications"], source: "Search Console location queries + live job registry + GA4", action: "Build or improve only the location with both real vacancies and search demand; avoid thin pages where either signal is absent." },
  11: { question: "Are legitimate relevant links improving discovery and qualified referral/organic visits?", kpis: ["impressions", "clicks", "organic_users"], source: "Backlinks tracker + Search Console Links/Pages + GA4 acquisition", action: "Focus outreach on one genuinely useful resource and high-relevance prospect; verify acquired links and review the target page monthly." },
  12: { question: "Did the evidence-led asset earn attention, links and visits from the intended audience?", kpis: ["organic_users", "clicks", "employer_leads"], source: "Backlinks tracker + GA4 referral/organic acquisition + Search Console", action: "Refine the asset or pitch using actual response and coverage data; never claim an outcome that the source data does not support." },
  13: { question: "Are direct, well-structured answers earning more visibility and useful clicks?", kpis: ["impressions", "ctr", "clicks"], source: "Search Console question queries/pages + Rich Results test", action: "Improve one answer block where impressions exist but CTR is weak; keep visible content and structured data consistent." },
  14: { question: "Are clearer entities, sources and original Malta information improving discovery?", kpis: ["impressions", "clicks", "ai_referrals"], source: "Search Console + GA4 AI referrals + AI Visibility tracker", action: "Strengthen one weak factual page with consistent organisation details, original evidence and cited sources, then record a dated observation." },
  15: { question: "Is Outreach surfaced or cited consistently, and does that visibility create visits?", kpis: ["ai_referrals", "organic_users", "employer_leads"], source: "AI Visibility tracker + GA4 source/medium and conversion events", action: "Repeat the fixed prompt set before acting; improve the most relevant source page only when several observations show the same gap." },
  16: { question: "Which 120-day changes produced credible business improvement and deserve the next investment?", kpis: ["clicks", "organic_users", "applications", "employer_leads"], source: "Daily KPI tracking + Experiments + final case study", action: "Compare equivalent periods, link each claimed win to evidence, and choose the next 90-day priorities by impact, confidence and effort." }
};
