/* Beginner "how to actually do it" layer for each course week.
   plain   = the lesson in simple words
   time    = realistic effort for the week
   days    = what to do on each of the 7 days (matches dailyRhythm)
   tasks   = exact clicks / method for each task in course-data.js (same order)
   example = a worked example using Outreach Recruitment
   done    = how to know the week is finished */
window.COURSE_HOWTO = {
  1: {
    plain: "Before you change anything, you take a 'photo' of how the website performs today. Search Console shows what happens in Google (how often you appear and get clicked). GA4 shows what people do after they arrive (do they click Apply?). Later you compare against this photo to prove what worked.",
    time: "About 3–4 hours this week (30–40 min per day).",
    days: [
      "Read this page top to bottom. Open search.google.com/search-console and analytics.google.com and check you can log in to both.",
      "Search Console → Performance → set date to 'Last 28 days' → Export → Google Sheets. Do it again for 'Last 3 months'. Paste both links in Task 3 notes.",
      "GA4 → Reports → Acquisition → Traffic acquisition. Filter 'Organic Search'. Write down users, sessions and key events. Then Engagement → Landing page: copy the top 10 pages.",
      "Draw the two journeys (Task 1 and 2) on paper or in a doc. Open the site on your phone and follow each journey yourself.",
      "Test events: open GA4 → Reports → Realtime. In another tab click 'Apply' on any job. Check 'apply_click' appears within ~30 seconds.",
      "Answer the 5 QCM questions in your own words, then click 'Show answer guide' and self-mark.",
      "Fill the KPI review table and the weekly résumé at the bottom. Mark the deliverable done with a link to your baseline doc.",
    ],
    tasks: [
      "Write 4 boxes: 1) someone googles 'chef jobs malta' → 2) lands on a job or sector page → 3) reads the job → 4) clicks Apply. Under each box write the real page URL. Do it yourself on your phone and note anything confusing (slow, hard to find the Apply button).",
      "Same idea for employers: 'recruitment agency malta' → homepage or employer page → contact/enquiry form → form sent. Note how many clicks it takes to reach the form. Fewer is better.",
      "Search Console → Performance → Search results. Tick all 4 boxes (Clicks, Impressions, CTR, Position). Date: 'Last 28 days' → Export. Repeat with 'Last 3 months'. Save both in a Drive folder called 'SEO Baseline'. Also add a row in Daily KPI tracking (the 'Log today's KPIs' button).",
      "GA4 → Reports → Acquisition → Traffic acquisition. Change the dimension to 'Session default channel group' and read the 'Organic Search' row. Then Reports → Engagement → Landing page. Screenshot both and save in the same folder.",
      "In GA4 → Admin → Events, check 'apply_click' and 'employer_lead_submit' exist. Turn both on as 'Key event' (the star / toggle). Write in the notes: 'Application = apply_click, Employer lead = employer_lead_submit'.",
    ],
    example: "Example baseline line: 'Last 28 days: 1,251 clicks, 31.7k impressions, CTR 3.9%, avg position 18. Homepage ranks ~9 for \"jobs in malta\".' That single sentence is what you compare against on Day 120.",
    done: "You have: 2 Search Console exports, 2 GA4 screenshots, 2 journey drawings, both events tested in Realtime, and the link to all of it in the deliverable box.",
  },
  2: {
    plain: "A keyword is just what people type into Google. Some people want a job (candidates), some want to hire (employers). For each important keyword you choose ONE page on the site that should rank for it. That list is your Keyword Master Sheet.",
    time: "About 4 hours this week.",
    days: [
      "Read the lesson. Open the Keywords tracker in the menu so you see the columns you will fill.",
      "Search Console → Performance → Queries tab → Last 3 months → Export. This is your list of real searches.",
      "In the export, add a column 'Intent' and label each query: Candidate / Employer / Information / Brand. Do the top 100 only.",
      "Type the general and sector keywords (Task 2 and 3) into Google. Write down which website is #1 for each and what type of page it is.",
      "Do the employer keywords (Task 4). These have few searches but each one can be a paying client.",
      "Fill Task 5 (one page per keyword) and answer the QCM.",
      "Add your top 20–30 keywords into the Keywords tracker. Fill the weekly review.",
    ],
    tasks: [
      "Search Console → Performance → click the 'Queries' tab under the chart → set 'Last 3 months' → Export → Google Sheets. Add an 'Intent' column. Rule of thumb: contains 'job', 'vacancy', 'work' = Candidate; 'hire', 'recruitment agency', 'staff' = Employer; 'how', 'what', 'salary' = Information; 'outreach' = Brand.",
      "Google each of: 'jobs in malta', 'recruitment agency malta', 'job vacancies malta'. Use an incognito window. Write: who is #1–3, and where is Outreach (count the results). Also note Search Console's position for each one.",
      "Make one tab per sector (hospitality, engineering, finance…). In each, list 5–10 searches like 'chef jobs malta', 'waiter jobs malta', 'hotel jobs malta'. Use Google's autocomplete and 'People also search for' at the bottom of results to find ideas.",
      "Same for employers: 'hire staff malta', 'recruitment services malta', 'find employees malta', 'staffing agency malta', 'hire chef malta'. Mark them Employer intent.",
      "Add a column 'Target page'. For every keyword write ONE URL, e.g. 'hospitality jobs malta' → /hospitality-jobs-in-malta/. If two pages could both fit, pick one and write 'CONFLICT' next to the other — that is cannibalisation, you fix it later.",
    ],
    example: "Row example: Keyword 'hospitality jobs malta' | Intent Candidate | Position 14 | Impressions 900 | Target page /hospitality-jobs-in-malta/ | Note: blog post 'hospitality-jobs-malta-guide' competes → CONFLICT.",
    done: "Keywords tracker has at least 20 rows, every row has an intent and one target page, and conflicts are flagged.",
  },
  3: {
    plain: "Each page should have one clear job. The title (blue link in Google), the H1 (big heading on the page) and the first lines must all say the same thing, in words people search. Internal links are links between your own pages — they help Google and visitors find the important ones.",
    time: "About 4–5 hours this week.",
    days: [
      "Read the lesson. Pick 5 pages: homepage, /jobs/, the employer page, and 2 sector pages.",
      "For each page right-click → 'View page source' → Ctrl/Cmd+F '<title' and '<h1'. Copy the current title and H1 into the Pages tracker.",
      "Write new title, meta description and H1 for each (Task 3). Keep title under ~60 characters.",
      "Make the changes on the site (or ask Claude Code to do them) and commit. Log each as an Experiment with today's date.",
      "Add internal links (Task 4). Check image alt text and buttons (Task 5).",
      "QCM.",
      "Weekly review. Write in the worksheet which page you changed and when you will check it (in 30 days).",
    ],
    tasks: [
      "Open the homepage. Ask: 'In one sentence, what is this page for?' (answer: jobs in Malta + recruitment agency). Check the <title> and the <h1> say that. If the H1 is a slogan like 'Welcome', that is a problem — write it down.",
      "Do the same for /jobs/ (should say 'Jobs in Malta – latest vacancies') and the employer page (should say 'Recruitment agency / hire staff in Malta').",
      "Template: Title = 'Main keyword | Benefit | Outreach Recruitment'. Meta = 1–2 sentences that make someone want to click, with a number if possible ('120+ live vacancies'). H1 = main keyword in natural words. Put old and new side by side in the Pages tracker.",
      "Open 3 blog posts. In each, add 1–2 links inside the text pointing to a sector page, using words that describe the page ('see current hospitality jobs in Malta'), not 'click here'. On each sector page link to its jobs, and on each job link back to its sector.",
      "Images: right-click → Inspect → check alt=\"…\" describes the image. Buttons: does every page have ONE obvious next action (Apply / Send CV / Contact us)? Note pages where it's missing.",
    ],
    example: "Before: <title>Home – Outreach</title>. After: <title>Jobs in Malta & Recruitment Agency | Outreach Recruitment</title>. Logged as Experiment 'Homepage title' on 2026-10-05, review on 2026-11-04.",
    done: "5 pages audited in the Pages tracker, at least 1 change published and logged as an Experiment, at least 5 new internal links added.",
  },
  4: {
    plain: "Technical SEO = making sure Google can reach and understand your pages. On a job site the big risks are: old closed jobs still in Google, the same page at two addresses (e.g. /jobs/chef.html and /jobs/chef/), and broken job data so you don't show in Google Jobs.",
    time: "About 4 hours this week.",
    days: [
      "Read the lesson. Open 'Technical audit' and 'Alerts' in the menu and read what is already found.",
      "Sitemap and robots (Task 1).",
      "Canonicals and duplicate URLs (Task 2) and expired jobs (Task 3).",
      "Job structured data test (Task 4).",
      "Speed test on mobile (Task 5).",
      "Give every issue a severity (Task 6). QCM.",
      "Weekly review. Fix 1–2 Critical issues or plan who fixes them.",
    ],
    tasks: [
      "Open outreachrecruitment.net/robots.txt — make sure it does NOT say 'Disallow: /' and that it lists the sitemap. Open the sitemap link. In Search Console → Sitemaps check status 'Success' and the number of discovered URLs. Search Console → Pages: note how many are 'Not indexed' and the reasons.",
      "Open a job page → View source → search 'canonical'. The URL there must be exactly the address you are on (with the trailing slash). Then try the same job with '.html' instead of '/' — if both open, write it as a duplicate issue.",
      "Pick a closed job from the registry. Open its URL: it should clearly say 'This position is closed' and suggest similar jobs, and it should NOT be in the sitemap. Write what actually happens.",
      "Go to search.google.com/test/rich-results, paste 3 job URLs (1 new, 1 old, 1 closed). Check 'Job posting' is detected with no red errors. Screenshot the results.",
      "Go to pagespeed.web.dev, test the homepage and one job page on Mobile. Write down LCP (should be under 2.5s), INP (under 200ms) and CLS (under 0.1).",
      "In the Technical tracker, add one row per problem with severity: Critical = stops Google indexing jobs; High = duplicates / wrong canonicals; Medium = slow pages; Low = cosmetic.",
    ],
    example: "Row: 'jobs/front-office-supervisor-2.html serves an older version than /jobs/front-office-supervisor-2/' | Severity High | Fix: rebuild flat .html | Status: open.",
    done: "Technical tracker has every issue with a severity, and at least the Critical ones are fixed or planned with a date.",
  },
  5: {
    plain: "A sector page is a permanent page like 'Hospitality Jobs in Malta'. Single jobs come and go, but the sector page stays and collects Google trust over time. It lists the live jobs and gives useful info for that sector.",
    time: "About 5 hours this week.",
    days: [
      "Read the lesson. Open 'Sectors & locations' to see which sectors have the most jobs and impressions.",
      "Review /hospitality-jobs-in-malta/ as if you were a candidate: is it useful? what is missing?",
      "Improve it (Task 1, 3, 4).",
      "Pick the second sector (Task 2) and write a short plan for its page.",
      "Add links to jobs and guides (Task 5). Log as Experiment.",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Open /hospitality-jobs-in-malta/. Check it has: a clear H1, 2–3 sentences about hospitality work in Malta, the list of current hospitality jobs, typical salaries if known, an FAQ, and an Apply/Send CV button. Add what is missing.",
      "Search Console → Performance → Queries → filter 'Query contains' e.g. 'engineer', then 'finance', 'logistics'. The sector with many impressions AND several live jobs on the site is your second choice.",
      "Make sure every live hospitality job is listed on the page with a link. When a job closes it should disappear from the list.",
      "Add 4–6 real questions candidates ask: 'Do I need Maltese?', 'Can non-EU workers apply?', 'What is the average waiter salary?'. Short honest answers.",
      "Link the sector page to each job, and from 2–3 related blog guides to the sector page. Log the change in Experiments with today's date.",
    ],
    example: "Second sector decision: 'Engineering: 2,100 impressions/3 months, avg position 22, 9 live jobs, no dedicated page → build Engineering Jobs in Malta.'",
    done: "Hospitality page improved and live, second sector chosen with numbers to justify it, both in the Pages tracker.",
  },
  6: {
    plain: "A topic cluster is a family of pages. One big 'pillar' page (Jobs in Malta) links down to sector pages and guides, and they link back up. This shows Google you cover the topic completely.",
    time: "About 4 hours this week.",
    days: [
      "Read the lesson. Draw a tree: Jobs in Malta at the top.",
      "Add sector pages under it (Task 2).",
      "Add guides (CV, interview, work permit) under the right branches (Task 3).",
      "Find orphan pages (Task 5).",
      "Add the missing links (Task 4).",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Decide the pillar: usually /jobs/ or the homepage — choose the one Google already ranks for 'jobs in malta' (check Search Console → Queries → 'jobs in malta' → Pages tab). Write what it must contain: overview, links to all sectors, links to key guides.",
      "List every sector page that exists (hospitality, retail, marine, insurance, …). Under each, write which jobs belong to it.",
      "List all blog guides (CV, interview, visa/work permit, salaries). Put each under the pillar or the sector it helps most.",
      "For each line in your tree, check a link actually exists in the page text. If not, add one with descriptive words.",
      "An orphan = a page that no other page links to. Check the Alerts/Technical audit for orphan findings, or in Search Console → Links → 'Top linked pages' see which pages have 0–1 internal links. Link each orphan from 1–2 related pages.",
    ],
    example: "Tree: Jobs in Malta → Hospitality → [chef, waiter jobs] + guide 'How to search hospitality jobs in Malta'. Missing link found: the guide didn't link to the hospitality page → added.",
    done: "A drawn cluster map, all missing links added, orphan list reduced.",
  },
  7: {
    plain: "Employers who search 'recruitment agency malta' are few, but one of them can be worth thousands of euros. This week you make the employer page convince them and make it very easy to send an enquiry.",
    time: "About 5 hours this week.",
    days: [
      "Read the lesson. Open the employer page and read it as a business owner who needs 5 waiters fast.",
      "Improve the employer page (Task 1 and 4).",
      "Write the plan for 'How to Hire Employees in Malta' (Task 2).",
      "Write the plan for 'Recruitment Process in Malta' (Task 3).",
      "Test the enquiry form in GA4 Realtime (Task 5).",
      "QCM.",
      "Weekly review: how many employer leads came from Google this week?",
    ],
    tasks: [
      "The page should answer in the first screen: who you are, which sectors you recruit for, how fast, and a big 'Request staff' button. Title example: 'Recruitment Agency in Malta – Hire Staff Fast | Outreach Recruitment'.",
      "Plan (don't write yet): H1, 5–7 section headings (e.g. 'Hiring EU vs non-EU workers', 'Costs', 'Timeline', 'Using an agency'), the keyword, and the CTA at the end. Save in Content tracker with status 'Planned'.",
      "Same for 'Recruitment Process in Malta': explain your steps 1-2-3-4 (brief → search → interviews → placement). This doubles as proof that you are professional.",
      "Add real proof only: number of placements, sectors served, client logos (with permission), a short testimonial. Never invent numbers.",
      "Open GA4 → Realtime, then send a test enquiry form. Check 'employer_lead_submit' appears. If it doesn't, write it as a High issue in Technical.",
    ],
    example: "CTA before: 'Contact us'. After: 'Tell us who you need to hire – reply within 24h' above the form.",
    done: "Employer page improved, 2 article plans saved, form event tested and working.",
  },
  8: {
    plain: "Improving an old page that already gets impressions is often faster than writing a new one. This week you find pages that are 'almost there' (position 4–20) or seen a lot but rarely clicked, and plan to improve them.",
    time: "About 4 hours this week.",
    days: [
      "Read the lesson. Open 'Site data' (live data) and the Pages tracker.",
      "Compare pages (Task 1).",
      "Find position 4–20 pages (Task 2).",
      "Find high-impression / low-CTR pages (Task 3).",
      "Find weak/outdated pages (Task 4).",
      "Build the 30-day queue (Task 5). QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Search Console → Performance → Pages tab → Last 3 months → Export. Add GA4 key events per landing page next to it (GA4 → Engagement → Landing page). Now you see visibility AND results per page.",
      "In the export, filter Position between 4 and 20. These are on page 1–2 of Google — a small improvement can move them to the top.",
      "Filter Impressions above ~500 and CTR below ~2%. People see the page but don't click → the title/description needs to be more attractive.",
      "Open the pages that are older than a year or mention old dates, closed jobs or wrong info. Mark them: Keep / Improve / Merge / Redirect.",
      "Pick 4–8 pages (one or two per week) and put them in the Pages tracker with a planned date. Each refresh = one Experiment, checked after 30 days.",
    ],
    example: "Page: 'construction-jobs-malta-non-eu-workers' | pos 7.8 | 3,400 impressions | CTR 1.1% → rewrite title to include '2026' and 'work permit' → Experiment.",
    done: "A 30-day refresh queue with a decision for every page, and the first refresh started.",
  },
  9: {
    plain: "Local SEO helps you appear for Malta searches and on Google Maps. Google trusts businesses whose name, address and phone (NAP) are the same everywhere, and who have a complete Google Business Profile and real reviews.",
    time: "About 3–4 hours this week.",
    days: [
      "Read the lesson. Write your official name, address, phone, website and opening hours in one place (the 'NAP master').",
      "Google 'Outreach Recruitment Malta' and check every listing against the NAP master (Task 1).",
      "Open business.google.com and complete the profile (Task 2).",
      "Check the descriptions (Task 3).",
      "Set up the review process (Task 4) and branded query tracking (Task 5).",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Google your company name. Open every result (Facebook, LinkedIn, directories, Google Maps). Compare name, address, phone with the NAP master. Write each difference in the Local tracker.",
      "business.google.com → your profile. Check: correct primary category ('Employment agency'), services listed, description, hours, photos, website link. Fill anything empty.",
      "Make sure the profile description and the website 'About' say the same thing: which sectors and which country markets you recruit from.",
      "Write a simple process: after a successful placement, send the client/candidate a message with the review link. Never pay or give gifts for reviews.",
      "Search Console → Performance → filter Query contains 'outreach' → note clicks/impressions. Do the same each month to see brand growth.",
    ],
    example: "Found: LinkedIn shows an old phone number → corrected → logged in Local tracker on 2026-10-05.",
    done: "NAP master written, all differences listed/fixed, Google profile complete, review process written.",
  },
  10: {
    plain: "You could make pages like 'Jobs in Sliema', but only if there are real jobs there and something useful to say. Ten copy-paste town pages are 'doorway pages' and can hurt the site. Citations are listings of your business on other websites.",
    time: "About 3–4 hours this week.",
    days: [
      "Read the lesson. In 'Sectors & locations', check how many live jobs are in each town.",
      "Rank locations (Task 1).",
      "Check existing pages for duplicates (Task 2).",
      "Find 10 citation sites (Task 3).",
      "Check info is consistent (Task 4) and write one page brief (Task 5).",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "For each town (Valletta, Sliema, St Julian's, Msida, Gozo…) write: number of live jobs, Search Console impressions for '[town] jobs', and one unique fact (e.g. St Julian's = hotels and iGaming). Keep only towns with jobs AND demand.",
      "If you already have town pages, read two side by side. If they are 80% the same text, merge them or rewrite with real local info.",
      "Google 'malta business directory', 'malta recruitment agencies list', chamber of commerce, Jobsplus partner lists. Note the ones that are real and relevant.",
      "For every directory where you are already listed, check NAP matches the master from Week 9.",
      "Brief = H1, why this town is useful for candidates, which jobs to show, 3 FAQs, and links. Only build it if Task 1 justifies it.",
    ],
    example: "Decision: 'Gozo: 6 live jobs, 300 impressions/3 months for \"jobs in gozo\" → brief written. Msida: 0 jobs → no page.'",
    done: "Location list with numbers, one brief, citation list in Local tracker.",
  },
  11: {
    plain: "A backlink is another website linking to you. A few links from real Malta organisations in your industry are worth more than hundreds of random ones. Buying links is risky — don't.",
    time: "About 4 hours this week.",
    days: [
      "Read the lesson. Decide which pages you want links to (e.g. a sector page or a useful guide).",
      "Find prospects (Task 1).",
      "Score them (Task 2).",
      "Look at existing partners (Task 3).",
      "Write and send the message (Task 4).",
      "QCM.",
      "Weekly review: log replies (Task 5).",
    ],
    tasks: [
      "Find 20 websites: language schools, universities, hotel associations, chambers of commerce, relocation blogs, expat groups in Malta, your clients' websites. Add each to the Links tracker.",
      "Give each a score 1–5 for 'Relevant to jobs/recruitment in Malta?' and 1–5 for 'Real organisation, not a link farm?'. Keep those with 7+ total.",
      "List companies you already work with (clients, schools, partners). Ask: could they link to us from a 'partners' or 'recruitment' page? These are the easiest wins.",
      "Short, personal email: who you are, one specific reason their readers benefit (e.g. 'our guide to work permits for students'), the link. No templates sent to everyone.",
      "In the Links tracker mark: contacted date, reply, link live yes/no. When a link goes live, open it and check it points to the right page.",
    ],
    example: "Prospect: a Malta English school | relevance 5 | legitimacy 5 | angle: 'Study and work in Malta' guide for their students → email sent 2026-10-08.",
    done: "20 prospects scored, at least 5 personal emails sent, everything logged.",
  },
  12: {
    plain: "Instead of asking for links, you create something others want to quote — for example a 'Malta Jobs Report' with real numbers from your own job data. Journalists and partners link to it naturally.",
    time: "About 4–5 hours this week.",
    days: [
      "Read the lesson. Brainstorm 3 report ideas.",
      "Choose one and list the data you have (Task 2).",
      "Find official sources to support it (Task 3).",
      "Write the page outline (Task 4).",
      "Build the list of people to send it to (Task 5).",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Example concept: 'Malta Recruitment Report Q4 2026 – which sectors are hiring, typical salaries, most-wanted roles'. Write the title, who it is for, and 3 headline findings you hope to show.",
      "From jobs_registry.json you can count: jobs per sector, per location, salaries shown, how long jobs stay open. Only use totals — never personal or client-confidential data.",
      "Add trusted public sources: NSO Malta, Jobsplus, Eurostat. Link them on the page so readers can check.",
      "Outline: short summary with 3 key numbers, charts, method ('based on X vacancies we published between …'), and a 'cite this report' line.",
      "List 15–20 targets: Times of Malta, Malta Independent, Lovin Malta business, chambers, HR groups, partners. One line each on why they would care.",
    ],
    example: "Finding: 'Hospitality = 38% of our live vacancies; median advertised salary €1,450/month' (only if the registry really shows it).",
    done: "Concept + method + outline + distribution list saved and linked in the deliverable.",
  },
  13: {
    plain: "AEO = writing so that a question gets a short, clear answer right away. That helps you appear in Google's answer boxes, 'People also ask' and AI answers. Answer first, then explain.",
    time: "About 4 hours this week.",
    days: [
      "Read the lesson. Start a list of questions.",
      "Collect the 50 questions (Task 1).",
      "Group them (Task 2).",
      "Write answers on 2–3 pages (Task 3).",
      "Add FAQs and links (Task 4 and 5). Test with the Rich Results Test.",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Sources: Search Console queries containing 'how', 'what', 'can', 'do I'; the 'People also ask' box when you Google 'jobs in malta'; and questions candidates/employers actually ask you by email or WhatsApp. Write 50 in a sheet.",
      "Add a column: Candidate / Employer / Sector / Location. Under each, pick which page should answer it.",
      "Under a heading that is the question, write a 1–2 sentence direct answer, then the detail. Example: 'Can non-EU citizens work in Malta? Yes, with a single permit applied for by the employer. The process usually takes…'.",
      "Add an FAQ block only where questions really belong on that page. If you add FAQ schema, the same questions and answers must be visible on the page.",
      "End each answer with a link to the deeper page (guide, sector page, apply page).",
    ],
    example: "Before: 3 paragraphs before saying salary. After: 'Average waiter salary in Malta: about €X/month (2026).' in the first line, then details.",
    done: "50 questions grouped, at least 10 answers published, schema tested without errors.",
  },
  14: {
    plain: "GEO = making your site a source that AI tools (ChatGPT, Gemini, Google AI Overviews) trust and cite. They prefer clear facts, dates, who wrote it, and real evidence — not vague marketing words.",
    time: "About 4–5 hours this week.",
    days: [
      "Read the lesson. Write a 'fact sheet' about Outreach Recruitment (Task 1).",
      "Make the About page and Organization schema match the fact sheet.",
      "Add dates/authors/sources to 2 guides (Task 2).",
      "Replace vague claims (Task 3) and restructure (Task 4).",
      "Upgrade one main guide (Task 5).",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Write 10 facts: legal name, founded year, address, sectors, countries recruited from, number of placements, languages, services, contact. Check the homepage, About and Google profile all say the same.",
      "On guides add 'Last updated: [date]' and 'Written by [name, role]'. When you state a rule (visa, salary), link the official source.",
      "Search the site for words like 'best', 'leading', 'thousands'. Replace with real numbers or remove.",
      "Use clear H2 headings as questions, short paragraphs, bullet lists and a table where you compare things (e.g. EU vs non-EU process).",
      "Pick one guide with good impressions and make it the best page on the internet for that topic in Malta: complete, up to date, sourced, with a summary at the top.",
    ],
    example: "'We are a leading agency' → 'Outreach Recruitment has placed X candidates in Malta since 20XX across hospitality, construction and retail.'",
    done: "Fact sheet done, one guide fully upgraded, claims cleaned on main pages.",
  },
  15: {
    plain: "You test whether AI assistants mention or link Outreach when people ask about jobs in Malta. Because AI answers change, you ask the SAME questions every time and write down the results with the date.",
    time: "About 2–3 hours this week, then ~1 hour per month.",
    days: [
      "Read the lesson. Open the AI visibility tracker.",
      "Write the 20 questions (Task 1).",
      "Run them in ChatGPT, Gemini, Perplexity and Google (AI Overview) (Task 2 and 3).",
      "Note competitors (Task 4).",
      "Check GA4 for AI traffic and set the repeat date (Task 5).",
      "QCM.",
      "Weekly review.",
    ],
    tasks: [
      "Examples: 'best recruitment agency in Malta', 'how to find a job in Malta as a foreigner', 'hospitality jobs in Malta', 'how to hire staff in Malta'. Save them — never change the wording later.",
      "Use a private/incognito window, not logged in if possible. For each question and tool write: date, tool, the question.",
      "For each answer mark: Mentioned (name appears) / Cited (link to your site) / Not present. Screenshot.",
      "Write which competitors appear and why they might be chosen (e.g. they have a salary guide).",
      "GA4 → Traffic acquisition → look for sources like chatgpt.com, perplexity.ai, gemini.google.com. Write the sessions. Put a reminder to repeat the test on the same day next month.",
    ],
    example: "2026-10-12 | Perplexity | 'how to find a job in Malta as a foreigner' | Cited (link to construction-jobs-malta-non-eu-workers) | competitors: Jobsplus, Indeed.",
    done: "20 questions × 3–4 tools recorded with date, and a monthly repeat date set.",
  },
  16: {
    plain: "Final week: compare where you started (Week 1 photo) with now, see what really worked, and plan the next 90 days. Be honest — things that didn't work are useful lessons too.",
    time: "About 4–5 hours.",
    days: [
      "Read the lesson. Open 'Final case study' — most numbers fill automatically.",
      "Export the same Search Console and GA4 reports as Week 1, same 28-day length (Task 1).",
      "Find winners and near-top-10 keywords (Task 2).",
      "Find pages with traffic but no applications (Task 3).",
      "List open technical work (Task 4).",
      "Write the 90-day plan (Task 5). QCM.",
      "Write the final summary and mark the course complete.",
    ],
    tasks: [
      "Same reports as Week 1, same length (last 28 days). Put Day 1 and Day 120 side by side: clicks, impressions, CTR, position, applications, employer leads.",
      "Search Console → Queries → filter position 4–15. These are the next quick wins. Also list the pages that grew most (Compare dates in Search Console).",
      "From the landing page report: pages with many sessions but few apply_click events. They need a better CTA or better job match.",
      "Open the Technical tracker, filter status 'open'. Copy the list into the plan.",
      "Score each idea Impact (1–5) and Effort (1–5). Pick 5 with high impact and low effort. Give each a target number and a review date.",
    ],
    example: "Priority 1: 'Get \"jobs in malta\" from position 9 to top 5 — refresh /jobs/ title + internal links from all sector pages. Target: +30% clicks by 2027-01-31.'",
    done: "Before/after table, every experiment concluded, 5 priorities with targets and dates.",
  },
};
